import image1 from "../../images/products/product1.png";
import image2 from "../../images/products/product2.png";
import image3 from "../../images/products/product3.png";
import { ProductDetails } from "../Product/Product.props";
export const defaultproducts: ProductDetails[] = [
    {
        productId: "p01",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image1,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 3,
        rentOnAdded: false,
    },
    {
        productId: "p02",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image2,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p03",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p04",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image1,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p05",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image2,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p06",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p07",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image1,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p08",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image2,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p09",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p10",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p11",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image1,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p12",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image2,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p13",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p14",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image1,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p15",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image2,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p16",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p17",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image1,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p18",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image2,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p19",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
    {
        productId: "p20",
        description: "Indore Palnt, Low Maintainance",
        ImageUrl: image3,
        productName: "Monsterra",
        actualCost: 350,
        currentCost: 299,
        isWhishListed: false,
        noOfItemsAddedToCart: 0,
        ratings: 4.9,
        rentOnAdded: false,
    },
];